# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo $(SYSTEM_ACCESSTOKEN)
  displayName: 'Print System Access Token'

- script: |
    curl -X GET https://app.vssps.visualstudio.com/_apis/profile/profiles/me -H "Authentication: Bearer $(SYSYSTEM_ACCESSTOKEN)"
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
