# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $headers = @{Authorization = "Bearer $env:SYSTEM_ACCESSTOKEN"}
      curl -Uri https://app.vssps.visualstudio.com/_apis/profile/profiles/me -Headers $headers
      Write-Host "Build.BuildUri:" $env:Build_BuildUri
      Write-Host "System.CollectionUri:" $env:System_CollectionUri
      Write-Host "System.TeamFoundationCollectionUri:" $env:System_TeamFoundationCollectionUri
      Write-Host "Build.Repository.Uri:" $env:Build_Repository_Uri
      Get-ChildItem Env: | Sort Name
