# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Write-Host "Build.BuildUri:" $env:Build_BuildUri
      Write-Host "System.CollectionUri:" $env:System_CollectionUri
      Write-Host "System.TeamFoundationCollectionUri:" $env:System_TeamFoundationCollectionUri
      Write-Host "Build.Repository.Uri:" $env:Build_Repository_Uri
- task: Semmle@1
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'csharp'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true